name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update APT database
      run: sudo apt-get -yq update || true
    - name: Install OS packages for building
      run: sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install bash
    - name: List of all installed packages
      run: dpkg -l | cat || true
    - name: Modifying the build system
      run: pwd ; hostname ; sudo hostname actions.github.com || true ; sudo adduser --home `pwd` --shell /bin/bash --no-create-home --disabled-password --disabled-login --gecos "LGB builder" lgb && sudo chown -R lgb:lgb .
    - name: Show system status
      run: cat /etc/debian_version ; lsb_release -a ; yacc --version | head -n 1 ; gcc --version | head -n 1 ; g++ --version | head -n 1 ; make --version | head -n 1 ; git --version | head -n 1 ; gawk --version | head -n 1 ; bash --version | head -n 1 ; uname -a ; id -a ; echo "CWD is `pwd`" ; echo "PATH is $PATH" ; echo "Hostname is `hostname`" ; sudo lscpu || true ; sudo lspci || true ; uptime ; sudo /sbin/ip a || true ; df -h . ; ls -la . ; env || true
    - name: THIS IS A DEMO main.yml ONLY
      run: echo "YEAH"
